name: Build Web Zip

on:
  workflow_dispatch: # Release Web

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git clone https://github.com/gitgitTrue/NextChatTempAPP.git

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1

      - name: Install @cloudflare/next-on-pages
        working-directory: ./NextChatTempAPP
        run: npm i @cloudflare/next-on-pages

      - name: Install Deps
        working-directory: ./NextChatTempAPP
        run: yarn install

      - name: Build Site
        working-directory: ./NextChatTempAPP
        run: npx @cloudflare/next-on-pages@1

      - name: Zip HTML
        working-directory: ./NextChatTempAPP/.vercel/output
        run: mv static web && zip -q -r web.zip ./web/

      - name: Move Zip File
        run: mkdir assets && ls ./NextChatTempAPP/.vercel/output/ && mv ./NextChatTempAPP/.vercel/output/web.zip ./assets/ && ls ./assets

      - name: Upload Web Zip
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            ./assets/web.zip
